[tool.poetry]
name = "cw4-oop"
version = "0.1.0"
description = ""
authors = ["Helen85236 <79532870251@yandex.ru>"]
readme = "README.md"
packages = [{include = "cw4"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
